# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "activerecord", require: 'active_record'
gem "mysql2"
gem "ridgepole"
